### ISSUE TITLE
BUG - Access Denied error when attempting to change File Metadata.

### ISSUE THREAD

**Issue by ParasiteDelta** [Kiramily/copycat#1]
It's nothing major, as the process appears to continue, but the `copy_file` function panics multiple times for any pre-existing file. To figure it out, I had to switch the `debug!` element in the function to `info!`, and it prints it clear as day. Personally, I don't care about the metadata, so I just removed it from my copy, but I just figured I would drop a note here in case you came back to this.

**Comment by ParasiteDelta** [comment]
And yes, I double-checked the general permissions for both the source and destination, and both are clear for general access.

**Comment by Kiramily** [comment]
Thanks for letting me know. I've added an argument to disable the metadata copying.
